### Gernelles
# venv aktivieren!
# cmd
# cd website-mkdocs
# .\venv\Scripts\activate.bat
# code .
# site_url: https://thomaschewski.de/

### Mkdocs
# https://squidfunk.github.io/mkdocs-material/reference/ 

### Link zur mkdocs.yml
# https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml#L135C3-L138C1
# https://github.com/james-willett/mkdocs-material-youtube-tutorial/blob/main/mkdocs.yml  (aus dem Video)
# https://squidfunk.github.io/mkdocs-material/getting-started/

### Blogging-Plugin schon installiert
# https://liang2kl.github.io/mkdocs-blogging-plugin/ 
# https://github.com/liang2kl/mkdocs-blogging-plugin

### VG WORT
# https://www.selbstaendig-im-netz.de/einnahmequellen/vg-wort-meldung-deadline-infos-zu-den-zaehlpixeln-geschaetze-einnahmen/
# <img style="display:none;" src="https://vg(123).met.vgwort.de/na/eine-lange-Reihe-von-Buchstaben-und-Ziffern" width="1" height="1" alt="">


site_name: Jörg Thomaschewski - Projekte - Forschung - Schulungen - Coaching
theme:
  name: material
  # name: material <- aus dem Video
  # name: readthedocs <- NEIN. Lizenz kostet Geld
  # name: windmill <- NEIN. wenig Konfigurationsmöglichkeiten
  # ansehen sphinx https://www.sphinx-doc.org/en/master/usage/quickstart.html 
  # https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes
  logo: assets/jt.jpg
  
  extra_css:
    - stylesheets/extras.css     # keine Ahnung, ob die eine Auswirkung hat https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#content-area-width 


  features:
    - navigation.tabs
    #- navigation.sections
    - navigation.footer # gibt einen Zurück-Button im Footer
    - navigation.tracking # siehe: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
    - navigation.expand
    - navigation.path
    - navigation.indexes 
    - navigation.top     # Pfeil nach oben wird angezeigt
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: de 
    
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Zum Dark-mode
      primary: green   # Hauptfarbe: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
      accent: red 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Zum Light-mode    
      primary: green
      accent: red

extra:
  # generator: false # unterdrückt Made with Material for MkDocs https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#generator-notice
  social:
    - icon: fontawesome/brands/google
      link: https://scholar.google.de/citations?user=-Oj8JzgAAAAJ
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Joerg_Thomaschewski
    - icon: fontawesome/brands/linkedin
      link: https://de.linkedin.com/in/j%C3%B6rg-thomaschewski-7074786/de
    - icon: fontawesome/brands/xing
      link: https://www.xing.com/profile/Joerg_Thomaschewski
    - icon: fontawesome/solid/envelope
      link: mailto:joerg.thomaschewski@hs-emden-leer.de 

markdown_extensions:
  - attr_list  # https://squidfunk.github.io/mkdocs-material/reference/grids/#using-card-grids
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.arithmatex:
      generic: true 
  - pymdownx.highlight:
      anchor_linenums: true 
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji

copyright: |
  &copy; 2023 für alle Inhalte Jörg Thomaschewski --- <a href="https://thomaschewski.de/weitere/Impressum.html">Impressum</a> --- <a href="https://thomaschewski.de/weitere/Datenschutzerkaerung.html">Datenschutzerklärung</a>